apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "andrew-quarkus-app"
  annotations:
    argocd/app-name: andrew-quarkus-app-dev
    backstage.io/kubernetes-id: andrew-quarkus-app
    github.com/project-slug: rhug-ottawa-janus/andrew-quarkus-app
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-p6whl.p6whl.sandbox2396.opentlc.com/#https://github.com/rhug-ottawa-janus/andrew-quarkus-app?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-p6whl.p6whl.sandbox2396.opentlc.com/#https://github.com/rhug-ottawa-janus/andrew-quarkus-app?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: CodeReady Workspaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "quarkus-team"
  providesApis:
    - "andrew-quarkus-app"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "andrew-quarkus-app"
spec:
  type: openapi
  lifecycle: production
  owner: "quarkus-team"
  definition:
    $text: ./openapi.yaml